# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQGIS_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgsmaplayercombobox import QgsMapLayerComboBox
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyQGISDialogBase(object):
    def setupUi(self, PyQGISDialogBase):
        PyQGISDialogBase.setObjectName("PyQGISDialogBase")
        PyQGISDialogBase.resize(563, 437)
        self.zakladki = QtWidgets.QTabWidget(PyQGISDialogBase)
        self.zakladki.setGeometry(QtCore.QRect(10, 0, 541, 431))
        self.zakladki.setObjectName("zakladki")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layer_text_label = QtWidgets.QLabel(self.tab)
        self.layer_text_label.setGeometry(QtCore.QRect(20, 0, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.layer_text_label.setFont(font)
        self.layer_text_label.setObjectName("layer_text_label")
        self.layer_MapLayer = QgsMapLayerComboBox(self.tab)
        self.layer_MapLayer.setGeometry(QtCore.QRect(10, 40, 160, 27))
        self.layer_MapLayer.setObjectName("layer_MapLayer")
        self.area_radioButton = QtWidgets.QRadioButton(self.tab)
        self.area_radioButton.setGeometry(QtCore.QRect(20, 190, 95, 20))
        self.area_radioButton.setAutoExclusive(True)
        self.area_radioButton.setObjectName("area_radioButton")
        self.height_radioButton = QtWidgets.QRadioButton(self.tab)
        self.height_radioButton.setGeometry(QtCore.QRect(20, 160, 95, 20))
        self.height_radioButton.setAutoFillBackground(False)
        self.height_radioButton.setAutoExclusive(True)
        self.height_radioButton.setObjectName("height_radioButton")
        self.calculate_Button = QtWidgets.QPushButton(self.tab)
        self.calculate_Button.setGeometry(QtCore.QRect(420, 300, 93, 28))
        self.calculate_Button.setObjectName("calculate_Button")
        self.napis_final_diffrence = QtWidgets.QLabel(self.tab)
        self.napis_final_diffrence.setGeometry(QtCore.QRect(200, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.napis_final_diffrence.setFont(font)
        self.napis_final_diffrence.setObjectName("napis_final_diffrence")
        self.calculate_napis = QtWidgets.QLabel(self.tab)
        self.calculate_napis.setGeometry(QtCore.QRect(20, 120, 60, 16))
        self.calculate_napis.setObjectName("calculate_napis")
        self.result_label = QtWidgets.QLabel(self.tab)
        self.result_label.setGeometry(QtCore.QRect(150, 270, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.result_label.setFont(font)
        self.result_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result_label.setText("")
        self.result_label.setTextFormat(QtCore.Qt.AutoText)
        self.result_label.setScaledContents(False)
        self.result_label.setObjectName("result_label")
        self.error_napis = QtWidgets.QLabel(self.tab)
        self.error_napis.setGeometry(QtCore.QRect(210, 330, 60, 16))
        self.error_napis.setObjectName("error_napis")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(29, 359, 481, 31))
        self.label.setObjectName("label")
        self.zakladki.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_coordinates_system = QtWidgets.QLabel(self.tab_2)
        self.label_coordinates_system.setGeometry(QtCore.QRect(60, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_coordinates_system.setFont(font)
        self.label_coordinates_system.setObjectName("label_coordinates_system")
        self.radioButton_2000 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_2000.setGeometry(QtCore.QRect(60, 40, 95, 20))
        self.radioButton_2000.setObjectName("radioButton_2000")
        self.radioButton_1992 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_1992.setGeometry(QtCore.QRect(60, 80, 95, 20))
        self.radioButton_1992.setObjectName("radioButton_1992")
        self.zakladki.addTab(self.tab_2, "")

        self.retranslateUi(PyQGISDialogBase)
        self.zakladki.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PyQGISDialogBase)

    def retranslateUi(self, PyQGISDialogBase):
        _translate = QtCore.QCoreApplication.translate
        PyQGISDialogBase.setWindowTitle(
            _translate("PyQGISDialogBase", "PyQGIS"))
        self.layer_text_label.setText(
            _translate("PyQGISDialogBase", "Choose layer"))
        self.area_radioButton.setText(_translate("PyQGISDialogBase", "Area"))
        self.height_radioButton.setText(
            _translate("PyQGISDialogBase", "Height"))
        self.calculate_Button.setText(
            _translate("PyQGISDialogBase", "Calculate"))
        self.napis_final_diffrence.setText(
            _translate("PyQGISDialogBase", "Result"))
        self.calculate_napis.setText(
            _translate("PyQGISDialogBase", "Calculate:"))
        self.error_napis.setText(_translate("PyQGISDialogBase", "Error"))
        self.label.setText(_translate("PyQGISDialogBase", "No errors "))
        self.zakladki.setTabText(self.zakladki.indexOf(
            self.tab), _translate("PyQGISDialogBase", "Height and area"))
        self.label_coordinates_system.setText(
            _translate("PyQGISDialogBase", "Układ współrzędnych"))
        self.radioButton_2000.setText(_translate("PyQGISDialogBase", "PL2000"))
        self.radioButton_1992.setText(_translate("PyQGISDialogBase", "PL1992"))
        self.zakladki.setTabText(self.zakladki.indexOf(
            self.tab_2), _translate("PyQGISDialogBase", "Load file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PyQGISDialogBase = QtWidgets.QDialog()
    ui = Ui_PyQGISDialogBase()
    ui.setupUi(PyQGISDialogBase)
    PyQGISDialogBase.show()
    sys.exit(app.exec_())
