# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQGIS_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyQGISDialogBase(object):
    def setupUi(self, PyQGISDialogBase):
        PyQGISDialogBase.setObjectName("PyQGISDialogBase")
        PyQGISDialogBase.resize(563, 437)
        self.layer_MapLayer = QgsMapLayerComboBox(PyQGISDialogBase)
        self.layer_MapLayer.setGeometry(QtCore.QRect(20, 60, 160, 27))
        self.layer_MapLayer.setObjectName("layer_MapLayer")
        self.layer_text_label = QtWidgets.QLabel(PyQGISDialogBase)
        self.layer_text_label.setGeometry(QtCore.QRect(70, 10, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.layer_text_label.setFont(font)
        self.layer_text_label.setObjectName("layer_text_label")
        self.calculate_Button = QtWidgets.QPushButton(PyQGISDialogBase)
        self.calculate_Button.setGeometry(QtCore.QRect(420, 380, 93, 28))
        self.calculate_Button.setObjectName("calculate_Button")
        self.result_label = QtWidgets.QLabel(PyQGISDialogBase)
        self.result_label.setGeometry(QtCore.QRect(240, 350, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.result_label.setFont(font)
        self.result_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result_label.setText("")
        self.result_label.setTextFormat(QtCore.Qt.AutoText)
        self.result_label.setScaledContents(False)
        self.result_label.setObjectName("result_label")
        self.napis_final_diffrence = QtWidgets.QLabel(PyQGISDialogBase)
        self.napis_final_diffrence.setGeometry(QtCore.QRect(250, 310, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.napis_final_diffrence.setFont(font)
        self.napis_final_diffrence.setObjectName("napis_final_diffrence")
        self.area_radioButton = QtWidgets.QRadioButton(PyQGISDialogBase)
        self.area_radioButton.setGeometry(QtCore.QRect(30, 150, 95, 20))
        self.area_radioButton.setAutoExclusive(True)
        self.area_radioButton.setObjectName("area_radioButton")
        self.height_radioButton = QtWidgets.QRadioButton(PyQGISDialogBase)
        self.height_radioButton.setGeometry(QtCore.QRect(30, 190, 95, 20))
        self.height_radioButton.setAutoFillBackground(False)
        self.height_radioButton.setAutoExclusive(True)
        self.height_radioButton.setObjectName("height_radioButton")
        self.label_coordinates_system = QtWidgets.QLabel(PyQGISDialogBase)
        self.label_coordinates_system.setGeometry(QtCore.QRect(370, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_coordinates_system.setFont(font)
        self.label_coordinates_system.setObjectName("label_coordinates_system")
        self.radioButton_2000 = QtWidgets.QRadioButton(PyQGISDialogBase)
        self.radioButton_2000.setGeometry(QtCore.QRect(370, 70, 95, 20))
        self.radioButton_2000.setObjectName("radioButton_2000")
        self.radioButton_1992 = QtWidgets.QRadioButton(PyQGISDialogBase)
        self.radioButton_1992.setGeometry(QtCore.QRect(370, 110, 95, 20))
        self.radioButton_1992.setObjectName("radioButton_1992")

        self.retranslateUi(PyQGISDialogBase)
        QtCore.QMetaObject.connectSlotsByName(PyQGISDialogBase)

    def retranslateUi(self, PyQGISDialogBase):
        _translate = QtCore.QCoreApplication.translate
        PyQGISDialogBase.setWindowTitle(_translate("PyQGISDialogBase", "PyQGIS"))
        self.layer_text_label.setText(_translate("PyQGISDialogBase", "Layer"))
        self.calculate_Button.setText(_translate("PyQGISDialogBase", "Calculate"))
        self.napis_final_diffrence.setText(_translate("PyQGISDialogBase", "Result"))
        self.area_radioButton.setText(_translate("PyQGISDialogBase", "Area"))
        self.height_radioButton.setText(_translate("PyQGISDialogBase", "Height"))
        self.label_coordinates_system.setText(_translate("PyQGISDialogBase", "Układ współrzędnych"))
        self.radioButton_2000.setText(_translate("PyQGISDialogBase", "PL2000"))
        self.radioButton_1992.setText(_translate("PyQGISDialogBase", "PL1992"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PyQGISDialogBase = QtWidgets.QDialog()
    ui = Ui_PyQGISDialogBase()
    ui.setupUi(PyQGISDialogBase)
    PyQGISDialogBase.show()
    sys.exit(app.exec_())
